
// Add 'as const' to preserve literal string types for properties, 
// ensuring they can be used as keys in Record types like Record<CalendarEventType, T>.
export const TEXT = {
  GLOBAL: {
    APP_TITLE: 'LiveTrack JP',
    APP_SUBTITLE: 'ライブ情報を効率的に追跡',
    COMMON_UNDEFINED: '未定',
    COMMON_UNKNOWN: '不明',
    COMMON_NOT_REGISTERED: '未登録',
    COMMON_NONE: 'なし',
    TBD: 'TBD',
  },
  STATUS: {
    発売前: '発売前',
    検討中: '検討中',
    抽選中: '抽選中',
    参戦予定: '参戦予定',
    参戦済み: '参戦済み',
    見送: '見送り',
  },
  ARTIST_STATUS: {
    MAIN_TOURING: 'ツアー中',
    MAIN_TRACKING: '公演追跡中',
    MAIN_NONE: '未追跡',
  },
  CALENDAR: {
    EVENT_CONCERT: '公演',
    EVENT_RESULT: '抽選結果',
    EVENT_SALE: '発売開始',
    EVENT_DEADLINE: '申込締切',
    WEEK_SUN: '日',
    WEEK_MON: '月',
    WEEK_TUE: '火',
    WEEK_WED: '水',
    WEEK_THU: '木',
    WEEK_FRI: '金',
    WEEK_SAT: '土',
  },
  LABELS: {
    DATE_UNDETERMINED: '日付未定',
    SCHEDULE_EMPTY: 'スケジュールはありません',
    CONCERT_SCHEDULE: '公演スケジュール',
    CONCERT_RECORD: '公演記録',
    LOTTERY_RESULT: '抽選結果',
    LOTTERY_RESULT_ANNOUNCE: '抽選結果発表',
    TICKET_PRICE: 'チケット料金',
    TICKET_SITE: '販売サイト',
    OFFICIAL_SITE: '公式サイト',
    ALBUM_TITLE: 'アルバム',
    MEMORIES_COUNT: '枚の思い出',
  },
  BUTTONS: {
    CONFIRM: '確定する',
    CANCEL: 'キャンセル',
    ADD: '追加する',
    EDIT: '編集する',
    SAVE: '保存する',
    DELETE: '削除する',
    BACK: '戻る',
    CLOSE: '閉じる',
    REFRESH: '更新',
    IMPORT: '読み込む',
    EXPORT: '書き出す',
    WON: '当選',
    LOST: '落選',
  },
  MENU: {
    DISPLAY_SETTINGS: '表示設定',
    SORT: '並び替え',
    DATA_MANAGEMENT: 'データ管理',
    SORT_MANUAL: '手動',
    SORT_STATUS: '状態順 (優先)',
    SORT_LOTTERY: '抽選結果日時順',
    AUTO_TRACK_INTERVAL: '自動追跡の間隔',
    SHOW_ATTENDED: '参戦済みを表示',
    SHOW_SKIPPED: '見送りを表示',
  },
  ALERTS: {
    TICKET_SALE_PERIOD: 'チケット販売・締切期間です',
    RESULT_ANNOUNCED: '抽選結果が出ている時間です',
    NEED_DATE_SETTING: '日時の設定が必要です',
    IMPORT_CONFIRM_TITLE: 'データを読み込む',
    IMPORT_CONFIRM_MSG: '選択されたファイルで現在のすべてのデータが上書きされます。よろしいですか？',
    DELETE_ARTIST_TITLE: 'アーティストを削除しますか？',
    DELETE_ARTIST_MSG: 'このアーティストに紐づくすべてのデータが完全に削除されます。',
    DELETE_TOUR_TITLE: 'ツアー削除',
    DELETE_TOUR_MSG: '全て削除されます。復元不可。',
    DUPLICATE_DATE_TITLE: '重複警告',
    DUPLICATE_DATE_MSG: '同日に他公演があります：',
  }
} as const;
