name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 确认你的分支名是 main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # 你的 Vite 配置中 build.outDir 应该是 docs
          branch: gh-pages